project:
  type: website
  output-dir: docs


website:
  title: "Brooklyn Holt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CAD_USD_Forcasting.qmd


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual



